version: '3.1'

services:

  rabbitmq:
    image: rabbitmq
    restart: always
    env_file:
      .env

  redis:
    image: redis
    restart: always

  mongo:
    image: mongo
    restart: always
    env_file:
      .env

  minio:
    image: minio/minio
    restart: always
    env_file:
      .env
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - ./tmp/minio:/data

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      .env
    ports:
      - 8081:8081

  gateway:
    build: apps/gateway
    restart: always
    env_file:
      .env
    ports:
      - 5000:80
    links:
      - core
      - minio

  core:
    build: apps/core
    restart: always
    env_file:
      .env
    links:
      - mongo

  celery:
    build: ./apps/celery
    restart: always
    env_file:
      .env
    links:
      - rabbitmq
      - redis
      - core
