version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    env_file:
      .env
    ports:
      - 15672:15672

  redis:
    image: redis
    restart: always

#  postgres:
#    image: postgres
#    restart: always
#    env_file:
#      .env
#    volumes:
#      - ./tmp/db_volume:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    env_file:
      .env
    ports:
    - 27017:27017

  minio:
    image: minio/minio
    restart: always
    env_file:
      .env
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - ./tmp/minio:/data

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      .env
    ports:
      - 8081:8081

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

  api-gate:
    build: ./apps/api_gate
    restart: always
    env_file:
      .env
    ports:
      - 5000:80
    links:
      - core
      - minio

  core:
    build: apps/core
    restart: always
    ports:
    - 5001:80
    env_file:
      .env
    links:
      - mongo

  celery:
    build: ./apps/celery
    restart: always
    env_file:
      .env
    links:
      - rabbitmq
      - redis
      - core
