version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "mypass"
    ports:
      - 15672:15672

  redis:
    image: redis
    restart: always

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "shop"
    volumes:
      - ./tmp/db_volume:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    volumes:
      - ./tmp/minio:/data

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api-gate:
    build: ./apps/api_gate
    restart: always
    environment:
      DB_TASKS: "http://api-db/tasks/"
    ports:
      - 5000:80
    links:
      - "api-db:api-db"

  api-db:
    build: ./apps/api_db
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres/shop"
    links:
      - "postgres:postgres"

  celery:
    build: ./apps/celery
    restart: always
    environment:
      BROKER_URL: "amqp://admin:mypass@rabbitmq:5672//"
      RESULT_BACKEND: "redis://redis:6379/0"
      C_FORCE_ROOT: "true"
      DB_TASKS: "http://api-db/tasks/"
      MONGO_URL: "mongodb://root:example@mongo:27017/"
      MONGO_DB: "docs"
    env_file:
      - ./apps/celery/.env
    links:
      - "rabbitmq:rabbitmq"
      - "redis:redis"
      - "api-db:api-db"
      - "mongo:mongo"
